# Generated by Django 2.0.3 on 2018-04-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny_emblems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.IntegerField()),
                ('membership_id', models.BigIntegerField()),
                ('player_data', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('membership_type', 'membership_id')},
        ),
    ]
