# Generated by Django 2.0.3 on 2018-04-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny_emblems', '0002_auto_20180417_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_data',
            field=models.TextField(null=True),
        ),
    ]
