# Generated by Django 2.0.3 on 2018-09-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny_emblems', '0003_auto_20180417_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emblem',
            name='index',
        ),
        migrations.AddField(
            model_name='emblem',
            name='collectible_hash',
            field=models.BigIntegerField(null=True),
        ),
    ]
